#!/bin/sh

. ./soxconfig

SUFFIX=$1
TIMEOUT=$2
FILE=mus${SUFFIX}

echo "Recording $TIMEOUT seconds of $FILE with sox options ${SOX_OPTS}..."

./${FILE} | sox ${SOX_OPTS}  - ${FILE}.wav trim 0 0:$TIMEOUT