#!/bin/sh

# you need sox to use this script
# also, be sure your files named "mus${SUFFIX}"

. ./soxconfig

SUFFIX=$1
FILE=mus${SUFFIX}

echo "Playing $FILE with options: ${SOX_OPTS}"
./${FILE} | play ${SOX_OPTS} -

